version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - playground-network
    command:
      - --performance-schema=OFF
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 300M

  backend:
    build:
      context: ./BE
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=secret
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - JAVA_TOOL_OPTIONS: "-Xmx200m -Xms200m"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - playground-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 350M

  frontend:
    build:
      context: ./FE
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - playground-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 150M

volumes:
  db_data:

networks:
  playground-network:
    driver: bridge
