spring.application.name=playground
spring.profiles.active= secret

spring.security.oauth2.client.registration.github.client-id= ${githyb.client-id}
spring.security.oauth2.client.registration.github.client-secret= ${github.client-secret}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}